/**
 * Generate TypeScript protocol types from the rbtr Python models.
 *
 * Shells out to `rbtr schema-dump`, merges every group's `$defs`
 * into one shared definitions map, and compiles a single combined
 * schema so each definition is emitted exactly once.
 *
 * Python is the source of truth.  Do not edit the generated file
 * by hand.  Re-run via `just schema-check`.
 */

import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile, type JSONSchema } from "json-schema-to-typescript";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(HERE, "..", "extensions", "rbtr", "generated", "protocol.ts");

const HEADER = `/**
 * AUTOGENERATED — do not edit by hand.
 *
 * Generated from the rbtr Python protocol models via
 * \`rbtr schema-dump\`.  Regenerate with \`just schema-check\`.
 *
 * Source of truth: packages/rbtr/src/rbtr/daemon/messages.py
 */

`;

interface ProtocolSchema {
  $defs: Record<string, JSONSchema>;
}

function runSchemaDump(): ProtocolSchema {
  const result = spawnSync("uv", ["run", "--package", "rbtr", "rbtr", "schema-dump"], {
    encoding: "utf8",
    cwd: join(HERE, "..", "..", ".."),
  });

  if (result.status !== 0) {
    process.stderr.write(result.stderr ?? "");
    throw new Error(`rbtr schema-dump exited with code ${result.status}`);
  }

  return JSON.parse(result.stdout) as ProtocolSchema;
}

async function main(): Promise<void> {
  // `rbtr schema-dump` runs one `models_json_schema` pass, so every
  // model is already a single shared `$defs` entry (no duplication to
  // merge).  The three message unions live under the bundle wrapper's
  // properties; lift them to named `$defs` so the compiler emits
  // `Request` / `Response` / `Notification` as union types.
  const { ProtocolSchema: bundle, ...memberDefs } = runSchemaDump().$defs;
  const bundleProps = (bundle.properties ?? {}) as Record<string, JSONSchema>;

  const combined: JSONSchema = {
    $defs: {
      ...memberDefs,
      Request: bundleProps.request,
      Response: bundleProps.response,
      Notification: bundleProps.notification,
    },
    type: "object",
    properties: {
      request: { $ref: "#/$defs/Request" },
      response: { $ref: "#/$defs/Response" },
      notification: { $ref: "#/$defs/Notification" },
      daemonstatusreport: { $ref: "#/$defs/DaemonStatusReport" },
    },
    title: "RbtrProtocol",
  };

  stripPropertyTitles(combined);
  stripRefSiblings(combined);
  requireKind(combined);

  const compiled = await compile(combined, "RbtrProtocol", {
    bannerComment: "",
    additionalProperties: false,
  });

  // Drop the synthetic root wrapper -- callers consume Request /
  // Response / Notification / CLI types directly.
  const withoutRoot = stripWrapper(compiled, "RbtrProtocol");

  const output = HEADER + withoutRoot;
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, output);

  const fmt = spawnSync("bunx", ["@biomejs/biome", "check", "--write", OUT_PATH], {
    stdio: ["ignore", "ignore", "inherit"],
  });
  if (fmt.status !== 0) {
    throw new Error(`biome check --write failed with code ${fmt.status}`);
  }

  process.stdout.write(`Wrote ${OUT_PATH}\n`);
}

/**
 * Strip sibling keywords from `$ref` nodes.
 *
 * Pydantic emits `{"$ref": "#/$defs/IndexVariant", "default": "full"}`
 * for fields that have a default.  json-schema-to-typescript treats
 * each such node as a distinct schema (because the sibling differs)
 * and emits `IndexVariant`, `IndexVariant1`, `IndexVariant2`, ... .
 * The `default` carries no type information for our purposes, so
 * dropping it merges every occurrence back to the single named type.
 */
function stripRefSiblings(schema: unknown): void {
  if (!schema || typeof schema !== "object") return;
  const node = schema as Record<string, unknown>;

  if ("$ref" in node) {
    for (const key of Object.keys(node)) {
      if (key !== "$ref") delete node[key];
    }
    return;
  }

  for (const value of Object.values(node)) {
    if (Array.isArray(value)) {
      for (const item of value) stripRefSiblings(item);
    } else if (value && typeof value === "object") {
      stripRefSiblings(value);
    }
  }
}

/**
 * Mark `kind` required on every object that has it as a property.
 *
 * Pydantic gives each message kind a default value, which makes
 * the field non-required in JSON Schema and therefore optional
 * in TypeScript.  But every real message on the wire has the
 * discriminator -- it has to, that's how the union works.
 * Without this fix `Request["kind"]` is `string | undefined`
 * and `Extract<Response, { kind: K }>` never narrows.
 */
function requireKind(schema: unknown): void {
  if (!schema || typeof schema !== "object") return;
  const node = schema as Record<string, unknown>;

  const props = node.properties;
  if (props && typeof props === "object" && "kind" in props) {
    const required = Array.isArray(node.required) ? [...(node.required as string[])] : [];
    if (!required.includes("kind")) required.push("kind");
    node.required = required;
  }

  for (const key of ["$defs", "definitions", "oneOf", "anyOf", "allOf", "items"]) {
    const child = node[key];
    if (Array.isArray(child)) {
      for (const item of child) requireKind(item);
    } else if (child && typeof child === "object") {
      for (const value of Object.values(child)) requireKind(value);
    }
  }
}

/**
 * Remove `title` from every sub-schema nested under `properties`.
 *
 * Pydantic labels each field with a title like `"Kind"` or
 * `"Repo"`; json-schema-to-typescript turns those into named
 * aliases.  Root-level titles (on `$defs` entries themselves)
 * are kept -- those become the real interface names.
 */
function stripPropertyTitles(schema: unknown): void {
  if (!schema || typeof schema !== "object") return;
  const node = schema as Record<string, unknown>;

  const props = node.properties;
  if (props && typeof props === "object") {
    for (const value of Object.values(props)) {
      if (value && typeof value === "object") {
        delete (value as Record<string, unknown>).title;
        stripPropertyTitles(value);
      }
    }
  }

  for (const key of ["$defs", "definitions", "oneOf", "anyOf", "allOf", "items"]) {
    const child = node[key];
    if (Array.isArray(child)) {
      for (const item of child) stripPropertyTitles(item);
    } else if (child && typeof child === "object") {
      for (const value of Object.values(child)) stripPropertyTitles(value);
    }
  }
}

/**
 * Drop the synthetic wrapper interface that the combined-schema
 * trick generates as a side effect.
 *
 * The wrapper is a single `export interface RbtrProtocol { ... }`
 * block that lists every group as a property.  We don't need it
 * downstream -- consumers import `Request`, `Response`, etc.
 * directly -- so strip it off the front.
 */
function stripWrapper(source: string, wrapperName: string): string {
  const lines = source.split("\n");
  const start = lines.findIndex((l) => l.startsWith(`export interface ${wrapperName}`));
  if (start < 0) return source;
  let end = start;
  while (end < lines.length && lines[end] !== "}") end++;
  // Skip the closing brace and any blank line after.
  let cut = end + 1;
  while (cut < lines.length && lines[cut].trim() === "") cut++;
  return [...lines.slice(0, start), ...lines.slice(cut)].join("\n");
}

main().catch((err: unknown) => {
  process.stderr.write(`${err instanceof Error ? (err.stack ?? err.message) : String(err)}\n`);
  process.exit(1);
});
