/**
 * Generate TypeScript protocol types from the rbtr Python models.
 *
 * Shells out to `rbtr schema-dump`, feeds the three top-level
 * groups (`request`, `response`, `notification`) through
 * `json-schema-to-typescript`, and writes one combined file.
 *
 * Python is the source of truth.  Do not edit the generated file
 * by hand.  Re-run via `just schema-check`.
 */

import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile, type JSONSchema } from "json-schema-to-typescript";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(HERE, "..", "extensions", "rbtr-index", "generated", "protocol.ts");

const HEADER = `/**
 * AUTOGENERATED — do not edit by hand.
 *
 * Generated from the rbtr Python protocol models via
 * \`rbtr schema-dump\`.  Regenerate with \`just schema-check\`.
 *
 * Source of truth: packages/rbtr/src/rbtr/daemon/messages.py
 */

`;

interface Schemas {
	request: JSONSchema;
	response: JSONSchema;
	notification: JSONSchema;
	cli: Record<string, JSONSchema>;
}

function runSchemaDump(): Schemas {
	// Uses `uv run --package rbtr` so the repo's workspace rbtr
	// is invoked regardless of what's on PATH.
	const result = spawnSync("uv", ["run", "--package", "rbtr", "rbtr", "schema-dump"], {
		encoding: "utf8",
		cwd: join(HERE, "..", "..", ".."),
	});

	if (result.status !== 0) {
		process.stderr.write(result.stderr ?? "");
		throw new Error(`rbtr schema-dump exited with code ${result.status}`);
	}

	const parsed = JSON.parse(result.stdout) as Schemas;
	return parsed;
}

async function main(): Promise<void> {
	const schemas = runSchemaDump();

	// Strip pydantic's property-level `title` fields before
	// compilation.  Without this, json-schema-to-typescript emits
	// a named alias for every titled property (`Kind`, `Kind1`,
	// `Repo`, `Repo1`, ...), which clutters the output.
	const cliSchemas = Object.values(schemas.cli);
	for (const schema of [schemas.request, schemas.response, schemas.notification, ...cliSchemas]) {
		stripPropertyTitles(schema);
		requireKind(schema);
	}

	const cliCompiled = await Promise.all(
		Object.entries(schemas.cli).map(([name, schema]) =>
			compile(schema, name, { bannerComment: "", additionalProperties: false }),
		),
	);

	const compiled = [
		await compile(schemas.request as JSONSchema, "Request", {
			bannerComment: "",
			additionalProperties: false,
		}),
		await compile(schemas.response as JSONSchema, "Response", {
			bannerComment: "",
			additionalProperties: false,
		}),
		await compile(schemas.notification as JSONSchema, "Notification", {
			bannerComment: "",
			additionalProperties: false,
		}),
		...cliCompiled,
	];

	// Dedupe shared $defs that reappear across groups
	// (ChunkKind, ImportMeta, etc.).
	const seen = new Set<string>();
	const deduped = compiled.map((block) => dedupeBlock(block, seen));

	const output = HEADER + deduped.join("\n");
	mkdirSync(dirname(OUT_PATH), { recursive: true });
	writeFileSync(OUT_PATH, output);

	// Run biome's formatter + import organiser so the file is
	// idempotent under `just lint-ts`.
	const fmt = spawnSync("bunx", ["@biomejs/biome", "check", "--write", OUT_PATH], {
		stdio: ["ignore", "ignore", "inherit"],
	});
	if (fmt.status !== 0) {
		throw new Error(`biome check --write failed with code ${fmt.status}`);
	}

	process.stdout.write(`Wrote ${OUT_PATH}\n`);
}

/**
 * Mark `kind` required on every object that has it as a property.
 *
 * Pydantic gives each message kind a default value, which makes
 * the field non-required in JSON Schema and therefore optional
 * in TypeScript.  But every real message on the wire has the
 * discriminator — it has to, that's how the union works.
 * Without this fix `Request["kind"]` is `string | undefined`
 * and `Extract<Response, { kind: K }>` never narrows.
 */
function requireKind(schema: unknown): void {
	if (!schema || typeof schema !== "object") return;
	const node = schema as Record<string, unknown>;

	const props = node.properties;
	if (props && typeof props === "object" && "kind" in props) {
		const required = Array.isArray(node.required) ? [...(node.required as string[])] : [];
		if (!required.includes("kind")) required.push("kind");
		node.required = required;
	}

	for (const key of ["$defs", "definitions", "oneOf", "anyOf", "allOf", "items"]) {
		const child = node[key];
		if (Array.isArray(child)) {
			for (const item of child) requireKind(item);
		} else if (child && typeof child === "object") {
			for (const value of Object.values(child)) requireKind(value);
		}
	}
}

/**
 * Remove `title` from every sub-schema nested under `properties`.
 *
 * Pydantic labels each field with a title like `"Kind"` or
 * `"Repo"`; json-schema-to-typescript turns those into named
 * aliases.  Root-level titles (on `$defs` entries themselves)
 * are kept — those become the real interface names.
 */
function stripPropertyTitles(schema: unknown): void {
	if (!schema || typeof schema !== "object") return;
	const node = schema as Record<string, unknown>;

	const props = node.properties;
	if (props && typeof props === "object") {
		for (const value of Object.values(props)) {
			if (value && typeof value === "object") {
				delete (value as Record<string, unknown>).title;
				stripPropertyTitles(value);
			}
		}
	}

	// Recurse into common schema container keys.
	for (const key of ["$defs", "definitions", "oneOf", "anyOf", "allOf", "items"]) {
		const child = node[key];
		if (Array.isArray(child)) {
			for (const item of child) stripPropertyTitles(item);
		} else if (child && typeof child === "object") {
			for (const value of Object.values(child)) stripPropertyTitles(value);
		}
	}
}

/**
 * Remove exported types whose name already appeared in an earlier
 * block.  Mutates *seen* with every name kept.
 *
 * Relies on json-schema-to-typescript's output shape: each type
 * starts at column 0 with `export (interface|type) <Name>`, and
 * ends at a line that is just `}` or `;` at column 0.
 */
function dedupeBlock(block: string, seen: Set<string>): string {
	const lines = block.split("\n");
	const out: string[] = [];
	let skip = false;
	for (const line of lines) {
		const match = line.match(/^export (?:interface|type) (\w+)/);
		if (match) {
			const name = match[1];
			if (seen.has(name)) {
				skip = true;
				continue;
			}
			seen.add(name);
			skip = false;
		}
		if (skip) {
			if (line === "}" || line === ";" || line.trim() === "") {
				skip = false;
				continue;
			}
			continue;
		}
		out.push(line);
	}
	return out.join("\n");
}

main().catch((err: unknown) => {
	process.stderr.write(`${err instanceof Error ? (err.stack ?? err.message) : String(err)}\n`);
	process.exit(1);
});
