"""Message-level operations on stored session history.

Four concerns, one data type (`list[ModelMessage]`):

- **Shared utilities** — `format_tool_args`, `is_compaction_summary`,
  `estimate_tokens`.
- **History repairs** — cross-provider compatibility and structural
  fixes applied transiently on each load.
- **Compaction helpers** — splitting, summarising, and building
  compaction summary messages.
- **Replay** — converting stored messages into display events
  (`replay_history`).

History rewrites
~~~~~~~~~~~~~~~~

LLM APIs require every `ToolCallPart` to have a matching
`ToolReturnPart` (same `tool_call_id`) and vice versa, and
require `ToolCallPart.args` to be valid JSON.  Providers also
encode tool exchanges in incompatible wire formats and reject
history containing metadata from other providers.

Nine mechanisms enforce these invariants at three stages.  All
repairs are **transient** — applied in memory on each load.
The persisted history is never modified.  See the *History
repair* section in the README for user-facing documentation.

Before each API call (level 0):

- `strip_orphaned_tool_returns` -- removes `ToolReturnPart`\\s
  whose `tool_call_id` has no matching `ToolCallPart` in the
  history.  Handles legacy sessions compacted before the
  `split_history` fix.  Recorded as ``strip_orphaned_returns``
  strategy.
- `validate_tool_call_args` -- repairs unparseable
  `ToolCallPart.args` to `{}`.
- `sanitize_tool_call_ids` -- replaces characters in
  `tool_call_id` values that violate provider patterns
  (e.g. Anthropic requires `^[a-zA-Z0-9_-]+$`).  IDs from
  other providers may contain dots, colons, etc.
- `repair_dangling_tool_calls` -- injects synthetic
  `(cancelled)` results for unmatched tool calls.  When
  partial returns already exist, synthetic results are merged
  into the same `ModelRequest` so every provider sees exactly
  one request with all returns per response.

On retry (after a provider rejection, two levels):

- `consolidate_tool_returns` (level 1) -- restructures tool
  returns so each response's returns are in one request.
  Handles cross-provider pairing mismatches without destroying
  content.  Recorded as `consolidate_tool_returns` strategy.
- `demote_thinking` (level 2) -- converts `ThinkingPart`
  to `TextPart` wrapped in `<thinking>` tags.
- `flatten_tool_exchanges` (level 2, last resort) -- converts
  `ToolCallPart` / `ToolReturnPart` to plain text,
  removing structural pairing entirely.  Recorded as
  `simplify_history` strategy.

On compaction (when splitting history):

- `split_history` -- moves orphaned tool returns into *old*.
  When a `ModelRequest` contains both a `UserPromptPart` (turn
  boundary) and orphaned `ToolReturnPart`\\s, the orphaned parts
  are stripped from the request.
- `snap_to_safe_boundary` -- adjusts split point to avoid
  separating tool-call / tool-result pairs.
"""

from __future__ import annotations

import json
import logging
import re
from collections.abc import Callable
from dataclasses import dataclass, replace
from typing import assert_never

from pydantic_ai.messages import (
    BuiltinToolCallPart,
    BuiltinToolReturnPart,
    FilePart,
    ModelMessage,
    ModelRequest,
    ModelRequestPart,
    ModelResponse,
    ModelResponsePart,
    RetryPromptPart,
    SystemPromptPart,
    TextPart,
    ThinkingPart,
    ToolCallPart,
    ToolReturnPart,
    UserPromptPart,
)

from rbtr.events import (
    Event,
    FlushPanel,
    InputEcho,
    MarkdownOutput,
    Output,
    PanelVariant,
    ToolCallFinished,
    ToolCallStarted,
)

from .kinds import SUMMARY_MARKER

log = logging.getLogger(__name__)


# ── Shared helpers ───────────────────────────────────────────────────


def format_tool_args(args: object) -> str:
    """Serialise `ToolCallPart.args` to a display string.

    `dict` → compact JSON, other truthy values → `str()`, `None` → `""`.
    """
    if isinstance(args, dict):
        return json.dumps(args, ensure_ascii=False)
    if args is not None:
        return str(args)
    return ""


def is_compaction_summary(text: str) -> bool:
    """Return whether *text* is a compaction summary message."""
    return text.startswith(SUMMARY_MARKER)


# ── Level-0 preventive repairs ────────────────────────────────────

# Anthropic requires tool_use IDs to match this pattern.
_TOOL_ID_RE = re.compile(r"^[a-zA-Z0-9_-]+$")
_TOOL_ID_BAD_CHARS = re.compile(r"[^a-zA-Z0-9_-]")


def sanitize_tool_call_ids(
    history: list[ModelMessage],
) -> tuple[list[ModelMessage], list[str]]:
    """Replace characters in `tool_call_id` that violate provider patterns.

    Anthropic requires tool_use IDs to match `^[a-zA-Z0-9_-]+$`.
    IDs generated by other providers (e.g. Google Gemini's
    `functions.tool_name:N` format) may contain dots, colons, or
    other characters that the target provider rejects.

    Builds a replacement map, then rewrites both `ToolCallPart`
    and `ToolReturnPart` / `RetryPromptPart` consistently so
    pairing is preserved.  Only IDs that actually contain invalid
    characters are touched.

    Returns `(history, bad_ids)` where *bad_ids* is the sorted
    list of original IDs that were sanitized (empty if none).
    """
    # Collect all tool_call_ids that need fixing.
    remap: dict[str, str] = {}
    for msg in history:
        if isinstance(msg, (ModelResponse, ModelRequest)):
            parts = msg.parts
        else:
            continue
        for p in parts:
            if isinstance(p, (ToolCallPart, ToolReturnPart, RetryPromptPart)):
                tid = p.tool_call_id
                if tid and not _TOOL_ID_RE.match(tid) and tid not in remap:
                    remap[tid] = _TOOL_ID_BAD_CHARS.sub("_", tid)

    if not remap:
        return history, []

    rebuilt: list[ModelMessage] = []
    for msg in history:
        if isinstance(msg, ModelResponse):
            new_parts: list[ModelResponsePart] = []
            for p in msg.parts:
                if isinstance(p, ToolCallPart) and p.tool_call_id in remap:
                    new_parts.append(replace(p, tool_call_id=remap[p.tool_call_id]))
                else:
                    new_parts.append(p)
            rebuilt.append(replace(msg, parts=new_parts))
        elif isinstance(msg, ModelRequest):
            req_parts: list[ModelRequestPart] = []
            for p in msg.parts:
                if isinstance(p, (ToolReturnPart, RetryPromptPart)) and p.tool_call_id in remap:
                    req_parts.append(replace(p, tool_call_id=remap[p.tool_call_id]))
                else:
                    req_parts.append(p)
            rebuilt.append(replace(msg, parts=req_parts))
        else:
            rebuilt.append(msg)

    log.info("Sanitized %d tool_call_id(s) with invalid characters.", len(remap))
    return rebuilt, sorted(remap)


def validate_tool_call_args(
    history: list[ModelMessage],
) -> list[tuple[str, str]]:
    """Ensure every `ToolCallPart` in *history* has parseable args.

    Repairs malformed `args` to `{}` in-place.  A model can
    produce invalid JSON during streaming (e.g. mixed XML/JSON
    fragments).  Replacing with `{}` preserves tool-call /
    tool-return pairing so the provider never rejects the history
    on account of orphaned returns.

    Returns a list of `(tool_name, tool_call_id)` pairs for
    every part whose args were repaired (empty if nothing changed).
    """
    repaired: list[tuple[str, str]] = []
    for msg in history:
        if not isinstance(msg, ModelResponse):
            continue
        for part in msg.parts:
            if isinstance(part, ToolCallPart):
                try:
                    part.args_as_dict(raise_if_invalid=True)
                except (ValueError, AssertionError):
                    log.info(
                        "Repairing corrupt args for tool call %s.",
                        part.tool_name,
                    )
                    part.args = {}
                    repaired.append((part.tool_name, part.tool_call_id))
    return repaired


# ── Result types ─────────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class DemoteResult:
    """Result of `demote_thinking`."""

    history: list[ModelMessage]
    parts_demoted: int


@dataclass(frozen=True, slots=True)
class FlattenResult:
    """Result of `flatten_tool_exchanges`."""

    history: list[ModelMessage]
    tool_calls_flattened: int
    tool_returns_flattened: int
    retry_prompts_dropped: int


def is_history_format_error(exc: Exception) -> bool:
    """Check if an API error is caused by malformed history items.

    Providers reject history for two broad reasons:

    * **Provider-specific metadata** -- reasoning IDs, thinking
      part formats, etc. that another provider doesn't recognise.
    * **Tool-call structure** -- pairing, ordering, or required
      fields that differ between wire formats.

    The patterns below are intentionally general (`tool_use` +
    `tool_result`, `required` + `field`, etc.) rather than
    matching specific model error strings, so they cover
    OpenAI-compatible endpoints that relay upstream errors in
    varying formats.
    """
    msg = str(exc).lower()
    # Reasoning ID rejected: "'input[6].id': 'reasoning_content'"
    if "invalid" in msg and ("'input[" in msg or ".id'" in msg):
        return True
    # Missing reasoning item: "provided without its required 'reasoning' item"
    if "provided without" in msg and "reasoning" in msg:
        return True
    # Unpaired tool calls: "tool_use ids ... without tool_result blocks"
    if "tool_use" in msg and "tool_result" in msg:
        return True
    # Gemini: "number of function response parts is equal to the number
    # of function call parts"
    if "function call" in msg and "function response" in msg:
        return True
    # Orphaned tool return: "No tool call found for function call output"
    if "no tool call found" in msg and "function call output" in msg:
        return True
    # Extra provider-specific fields rejected by a different provider
    # (e.g. OpenAI Responses API reasoning IDs sent to Fireworks):
    # "Extra inputs are not permitted, field: 'messages[1].rs_...'"
    if "extra inputs are not permitted" in msg:
        return True
    # Tool-use ID contains characters rejected by the target provider
    # (Anthropic requires ^[a-zA-Z0-9_-]+$):
    # "tool_use.id: String should match pattern '^[a-zA-Z0-9_-]+'"
    if "tool_use" in msg and "should match pattern" in msg:
        return True
    # Required field missing from a message (e.g. null content on an
    # assistant message that contains only tool calls).
    return "required" in msg and "field" in msg


def demote_thinking(history: list[ModelMessage]) -> DemoteResult:
    """Return history with ThinkingParts converted to plain TextParts.

    Wraps thinking content in `<thinking>` tags so the model can
    still see prior reasoning, without the provider-specific IDs
    that cause cross-provider errors.
    """
    cleaned: list[ModelMessage] = []
    parts_demoted = 0
    for msg in history:
        if isinstance(msg, ModelResponse):
            new_parts: list[ModelResponsePart] = []
            for p in msg.parts:
                if isinstance(p, ThinkingPart):
                    if p.content:
                        new_parts.append(TextPart(content=f"<thinking>\n{p.content}\n</thinking>"))
                        parts_demoted += 1
                    # Empty thinking parts are dropped (no increment).
                else:
                    new_parts.append(p)
            if new_parts:
                cleaned.append(replace(msg, parts=new_parts))
        else:
            cleaned.append(msg)
    return DemoteResult(history=cleaned, parts_demoted=parts_demoted)


def _is_exact_tool_return(request: ModelRequest, expected_ids: set[str]) -> bool:
    """True if *request* contains only tool returns matching *expected_ids*."""
    returns = [p for p in request.parts if isinstance(p, (ToolReturnPart, RetryPromptPart))]
    return len(returns) == len(request.parts) and {p.tool_call_id for p in returns} == expected_ids


@dataclass(frozen=True, slots=True)
class ConsolidateResult:
    """Result of `consolidate_tool_returns`."""

    history: list[ModelMessage]
    turns_fixed: int


def consolidate_tool_returns(history: list[ModelMessage]) -> ConsolidateResult:
    """Restructure tool returns so each response's returns are in one request.

    Providers require that a model turn with N tool calls is followed
    by exactly one user turn with N tool results.  Valid histories can
    violate this when:

    * Tool returns are scattered across multiple `ModelRequest`\\s
      (e.g. after compaction or mid-turn cancellation).
    * A `ModelRequest` mixes `ToolReturnPart`\\s with
      `UserPromptPart`\\s — some adapters split these into separate
      content objects, breaking the count.

    This function consolidates: for each `ModelResponse` with tool
    calls, it collects all matching `ToolReturnPart`\\s and
    `RetryPromptPart`\\s (by `tool_call_id`) from subsequent
    requests, places them in a single `ModelRequest` immediately
    after the response, and moves non-tool parts to a separate
    request.  All content is preserved — only the grouping changes.

    Lighter than `flatten_tool_exchanges` (which destroys
    structural pairing).  Used on the first retry; flatten is the
    last resort.
    """
    if not history:
        return ConsolidateResult(history=history, turns_fixed=0)

    # Index: tool_call_id → part, for all tool returns in the history.
    return_index: dict[str | None, ToolReturnPart | RetryPromptPart] = {
        p.tool_call_id: p
        for msg in history
        if isinstance(msg, ModelRequest)
        for p in msg.parts
        if isinstance(p, (ToolReturnPart, RetryPromptPart)) and p.tool_call_id
    }

    rebuilt: list[ModelMessage] = []
    consumed_ids: set[str | None] = set()  # tool_call_ids placed by consolidation
    turns_fixed = 0
    i = 0
    while i < len(history):
        msg = history[i]
        if isinstance(msg, ModelResponse):
            call_ids = [p.tool_call_id for p in msg.parts if isinstance(p, ToolCallPart)]
            if call_ids:
                # Skip if next request already has exactly the right
                # returns and nothing else.
                next_msg = history[i + 1] if i + 1 < len(history) else None
                expected = set(call_ids)
                if isinstance(next_msg, ModelRequest) and _is_exact_tool_return(next_msg, expected):
                    rebuilt.append(msg)
                    rebuilt.append(next_msg)
                    consumed_ids.update(call_ids)
                    i += 2
                    continue

                # Collect returns for these calls from anywhere in
                # the history.
                returns: list[ModelRequestPart] = []
                for cid in call_ids:
                    ret = return_index.get(cid)
                    if ret is not None:
                        returns.append(ret)
                        consumed_ids.add(cid)
                    else:
                        returns.append(
                            ToolReturnPart(
                                tool_name="unknown",
                                content="(cancelled)",
                                tool_call_id=cid,
                            )
                        )

                rebuilt.append(msg)
                rebuilt.append(ModelRequest(parts=returns))
                turns_fixed += 1
                i += 1
                continue

        # For ModelRequests, strip out parts that were already consumed
        # by consolidation and keep the rest.
        if isinstance(msg, ModelRequest):
            remaining = [
                p
                for p in msg.parts
                if not (
                    isinstance(p, (ToolReturnPart, RetryPromptPart))
                    and p.tool_call_id in consumed_ids
                )
            ]
            if remaining:
                rebuilt.append(replace(msg, parts=remaining))
        else:
            rebuilt.append(msg)
        i += 1

    if turns_fixed:
        return ConsolidateResult(history=rebuilt, turns_fixed=turns_fixed)
    return ConsolidateResult(history=history, turns_fixed=0)


def flatten_tool_exchanges(history: list[ModelMessage]) -> FlattenResult:
    """Convert tool-call exchanges into plain text.

    Cross-provider last resort
    ~~~~~~~~~~~~~~~~~~~~~~~~~~

    Each provider encodes tool-call / tool-result exchanges in its own
    wire format (Anthropic `tool_use` / `tool_result` blocks, OpenAI
    `function_call` items, etc.).  PydanticAI translates between them,
    but edge cases in complex histories (multi-turn tool-call chains,
    compaction boundaries, partial streaming saves) can produce
    structures that the *target* provider's adapter rejects — even
    though `repair_dangling_tool_calls` already ensured every
    `ToolCallPart` has a matching `ToolReturnPart` in the internal
    representation.

    This function eliminates the structural pairing entirely by
    converting the parts to plain text:

    * `ToolCallPart`  -> `TextPart("[Repaired historical tool call -- tool_name(args)]")`
    * `ToolReturnPart` -> `UserPromptPart("[Repaired historical tool result -- tool_name]\\n...")`
    * `RetryPromptPart` — dropped (only meaningful to the original
      provider).

    All content survives — file contents, grep output, diff patches
    etc. remain in the history as readable text.  Only the machine-
    level call/result pairing is removed.

    When it runs
    ~~~~~~~~~~~~

    Never on the first attempt.  The retry path is:

    1. Level 0: `repair_dangling_tool_calls` on load.
    2. Level 1: `consolidate_tool_returns` (restructure only).
    3. Level 2: `demote_thinking` + *this function* (last resort).

    This function only runs at level 2 — after consolidation
    failed to satisfy the provider.
    """
    cleaned: list[ModelMessage] = []
    tool_calls_flattened = 0
    tool_returns_flattened = 0
    retry_prompts_dropped = 0
    for msg in history:
        if isinstance(msg, ModelResponse):
            resp_parts: list[ModelResponsePart] = []
            for rp in msg.parts:
                if isinstance(rp, ToolCallPart):
                    tool_calls_flattened += 1
                    label = f"[Repaired historical tool call -- {rp.tool_name}({format_tool_args(rp.args)})]"
                    resp_parts.append(TextPart(content=label))
                else:
                    resp_parts.append(rp)
            cleaned.append(ModelResponse(parts=resp_parts, model_name=msg.model_name))
        elif isinstance(msg, ModelRequest):
            req_parts: list[ModelRequestPart] = []
            for qp in msg.parts:
                if isinstance(qp, ToolReturnPart):
                    tool_returns_flattened += 1
                    text = f"[Repaired historical tool result -- {qp.tool_name}]\n{qp.content}"
                    req_parts.append(UserPromptPart(content=text))
                elif isinstance(qp, RetryPromptPart):
                    retry_prompts_dropped += 1
                else:
                    req_parts.append(qp)
            if req_parts:
                cleaned.append(ModelRequest(parts=req_parts))
        else:
            cleaned.append(msg)
    return FlattenResult(
        history=cleaned,
        tool_calls_flattened=tool_calls_flattened,
        tool_returns_flattened=tool_returns_flattened,
        retry_prompts_dropped=retry_prompts_dropped,
    )


# ── Dangling tool-call repair ────────────────────────────────────────


def strip_orphaned_tool_returns(
    history: list[ModelMessage],
) -> tuple[list[ModelMessage], list[str]]:
    """Remove `ToolReturnPart`s that have no matching `ToolCallPart`.

    **When this fires:** Orphaned returns appear in sessions that
    were compacted before the `split_history` fix that strips
    orphaned parts during the split.  The scenario: a tool call
    in turn N has its return in a mixed `ModelRequest` (containing
    both `ToolReturnPart` and `UserPromptPart`) at the start of
    turn N+1.  Compaction removes turn N (including the call) but
    keeps turn N+1 (because it has the user prompt).  The return
    is left without a matching call.

    **Why it still runs:** `split_history` now prevents new orphans,
    but sessions compacted by older code may have orphaned returns
    persisted in the DB.  Since history is immutable (never modified
    on disk), this load-time repair strips them transiently.  An
    ``LLM_HISTORY_REPAIR`` incident with strategy
    ``STRIP_ORPHANED_RETURNS`` is recorded when stripping occurs.

    Returns ``(repaired_history, stripped_call_ids)`` — does not
    mutate the originals.
    """
    call_ids: set[str] = set()
    for msg in history:
        if isinstance(msg, ModelResponse):
            for p in msg.parts:
                if isinstance(p, ToolCallPart) and p.tool_call_id:
                    call_ids.add(p.tool_call_id)

    stripped: list[str] = []
    result: list[ModelMessage] = []
    for msg in history:
        if isinstance(msg, ModelRequest):
            cleaned: list[ModelRequestPart] = []
            for req_part in msg.parts:
                if isinstance(req_part, ToolReturnPart) and req_part.tool_call_id not in call_ids:
                    stripped.append(req_part.tool_call_id)
                else:
                    cleaned.append(req_part)
            if len(cleaned) != len(msg.parts):
                result.append(ModelRequest(parts=cleaned))
                continue
        result.append(msg)
    return result, stripped


def repair_dangling_tool_calls(
    history: list[ModelMessage],
) -> tuple[list[ModelMessage], list[str], list[str]]:
    """Fix history left dirty by a cancelled tool-calling turn.

    Part of the tool-call pairing invariant (see module docstring).
    For each `ModelResponse` with `ToolCallPart`\\s, checks whether
    every call has a matching `ToolReturnPart` *anywhere* in the
    history.  Injects a synthetic `(cancelled)` result for any
    truly unmatched call.  When partial results already exist in the
    next `ModelRequest`, synthetic returns are merged into it so
    every provider sees exactly one request with all returns.

    Applied transiently on each session load — the persisted history
    is never modified.

    Returns `(repaired_history, tool_names, tool_call_ids)` where
    *tool_names* lists every tool that was patched and
    *tool_call_ids* lists the corresponding IDs (both empty if no
    repair needed).
    """
    if not history:
        return history, [], []

    # Collect all tool_call_ids that already have a matching return
    # anywhere in the history — prevents false positives when a user
    # prompt is interleaved between calls and returns.
    globally_answered: set[str | None] = {
        p.tool_call_id
        for msg in history
        if isinstance(msg, ModelRequest)
        for p in msg.parts
        if isinstance(p, (ToolReturnPart, RetryPromptPart))
    }

    repaired: list[ModelMessage] | None = None  # lazy copy
    all_tool_names: list[str] = []
    all_tool_call_ids: list[str] = []

    i = 0
    while i < len(history):
        msg = history[i]
        if isinstance(msg, ModelResponse):
            tool_calls = [p for p in msg.parts if isinstance(p, ToolCallPart)]
            if tool_calls:
                missing = [tc for tc in tool_calls if tc.tool_call_id not in globally_answered]
                if missing:
                    if repaired is None:
                        repaired = list(history[:i])
                    repaired.append(msg)

                    all_tool_names.extend(tc.tool_name for tc in missing)
                    all_tool_call_ids.extend(tc.tool_call_id for tc in missing)
                    log.info(
                        "Repairing %d dangling tool call(s) from cancelled turn.",
                        len(missing),
                    )
                    synthetic_parts: list[ModelRequestPart] = [
                        ToolReturnPart(
                            tool_name=tc.tool_name,
                            content="(cancelled)",
                            tool_call_id=tc.tool_call_id,
                        )
                        for tc in missing
                    ]

                    # Merge synthetic returns into the existing request
                    # so the provider sees one request with ALL returns
                    # for this response.  Gemini (and others) require
                    # the count to match exactly.
                    next_msg = history[i + 1] if i + 1 < len(history) else None
                    if isinstance(next_msg, ModelRequest) and any(
                        isinstance(p, (ToolReturnPart, RetryPromptPart)) for p in next_msg.parts
                    ):
                        merged = replace(
                            next_msg,
                            parts=list(next_msg.parts) + synthetic_parts,
                        )
                        repaired.append(merged)
                        i += 1  # skip next_msg, replaced by merged
                    else:
                        repaired.append(ModelRequest(parts=synthetic_parts))
                    i += 1
                    continue
        if repaired is not None:
            repaired.append(msg)
        i += 1

    if repaired is not None:
        return repaired, all_tool_names, all_tool_call_ids
    return history, [], []


# ── Compaction helpers ───────────────────────────────────────────────


def _tool_ids(messages: list[ModelMessage]) -> tuple[set[str], set[str]]:
    """Return `(call_ids, result_ids)` from *messages*."""
    call_ids: set[str] = set()
    result_ids: set[str] = set()
    for msg in messages:
        match msg:
            case ModelResponse():
                for p in msg.parts:
                    match p:
                        case ToolCallPart(tool_call_id=tid) if tid:
                            call_ids.add(tid)
            case ModelRequest():
                for p in msg.parts:  # type: ignore[assignment]  # request vs response part types
                    match p:
                        case (
                            ToolReturnPart(tool_call_id=tid) | RetryPromptPart(tool_call_id=tid)
                        ) if tid:
                            result_ids.add(tid)
    return call_ids, result_ids


def _has_user_prompt(msg: ModelMessage) -> bool:
    """True if *msg* is a `ModelRequest` containing a `UserPromptPart`."""
    return isinstance(msg, ModelRequest) and any(isinstance(p, UserPromptPart) for p in msg.parts)


def split_history(
    history: list[ModelMessage],
    keep_turns: int,
) -> tuple[list[ModelMessage], list[ModelMessage]]:
    """Split history into (old, kept) by user turn count.

    A *turn* starts at a `ModelRequest` containing a `UserPromptPart`
    and includes all subsequent messages until the next such request.

    Returns `(old, kept)` where `kept` has the last *keep_turns*
    turns and `old` has everything before.  If the history has
    `keep_turns` or fewer turns, `old` is empty.

    After the initial split, messages with broken tool-call pairing
    are moved from `kept` to `old`:

    - Tool-return-only requests whose call IDs have no matching
      `ToolCallPart` in `kept` (orphaned results).
    - `ModelResponse` messages with `ToolCallPart`s that have no
      matching result in `kept` (cancelled turns).
    """
    turn_starts = [i for i, msg in enumerate(history) if _has_user_prompt(msg)]

    if len(turn_starts) <= keep_turns:
        return [], list(history)

    cut = turn_starts[-keep_turns]
    old, kept = list(history[:cut]), list(history[cut:])

    # Move unpaired tool messages from kept to old until stable.
    # Each pass may expose new orphans (moving a result orphans
    # the call, and vice versa), so repeat until nothing moves.
    clean = kept
    while True:
        call_ids, result_ids = _tool_ids(clean)
        moved: list[ModelMessage] = []
        remaining: list[ModelMessage] = []
        changed = False
        for msg in clean:
            match msg:
                case ModelRequest() if not _has_user_prompt(msg):
                    _, rids = _tool_ids([msg])
                    if rids and rids.isdisjoint(call_ids):
                        moved.append(msg)
                        changed = True
                        continue
                case ModelRequest() if _has_user_prompt(msg):
                    # Mixed request with both UserPromptPart and
                    # orphaned ToolReturnParts: strip orphaned parts.
                    # Creates a new ModelRequest to preserve the
                    # original for DB identity matching.
                    _, rids = _tool_ids([msg])
                    orphaned = rids - call_ids
                    if orphaned:
                        cleaned = ModelRequest(
                            parts=[
                                p
                                for p in msg.parts
                                if not (
                                    isinstance(p, ToolReturnPart) and p.tool_call_id in orphaned
                                )
                            ]
                        )
                        remaining.append(cleaned)
                        changed = True
                        continue
                case ModelResponse():
                    cids, _ = _tool_ids([msg])
                    if cids and cids.isdisjoint(result_ids):
                        moved.append(msg)
                        changed = True
                        continue
            remaining.append(msg)
        if not changed:
            break
        old.extend(moved)
        clean = remaining

    return old, clean


def snap_to_safe_boundary(messages: list[ModelMessage], count: int) -> int:
    """Adjust *count* so a split at that index never separates a
    `ModelResponse` (tool calls) from its `ModelRequest` (tool results).

    A `ModelResponse` with `ToolCallPart`\\s must stay in the same
    partition as the immediately following `ModelRequest`.  If
    *count* would split them, it is reduced until the boundary is safe.

    Returns the adjusted count (may be 0 if no safe split exists).
    """
    while count > 0:
        prev = messages[count - 1]
        if isinstance(prev, ModelResponse) and any(isinstance(p, ToolCallPart) for p in prev.parts):
            count -= 1
        else:
            break
    return count


def estimate_tokens(text: str) -> int:
    """Rough token estimate: 1 token ≈ 4 characters."""
    return len(text) // 4


def serialise_for_summary(
    messages: list[ModelMessage],
    max_tool_chars: int = 2_000,
) -> str:
    """Convert messages to a human-readable text for the summary prompt.

    Tool return content is truncated to *max_tool_chars* to keep the
    serialised output manageable.  Thinking parts are omitted.
    """
    sections: list[str] = []

    for msg in messages:
        match msg:
            case ModelRequest(parts=req_parts):
                for req_part in req_parts:
                    match req_part:
                        case UserPromptPart(content=content):
                            text = content if isinstance(content, str) else str(content)
                            sections.append(f"## User\n{text}")
                        case ToolReturnPart(tool_name=name, content=content):
                            text = str(content)
                            if len(text) > max_tool_chars:
                                text = text[:max_tool_chars] + "…[truncated]"
                            sections.append(f"## Tool result: {name}\n{text}")
            case ModelResponse(parts=resp_parts):
                for resp_part in resp_parts:
                    match resp_part:
                        case TextPart(content=content):
                            sections.append(f"## Assistant\n{content}")
                        case ToolCallPart(tool_name=name, args=args):
                            sections.append(f"## Tool call: {name}({format_tool_args(args)})")
                        # ThinkingPart — omit from summary input

    return "\n\n".join(sections)


def build_summary_message(summary_text: str) -> ModelRequest:
    """Create a synthetic first message containing the compaction summary."""
    content = f"{SUMMARY_MARKER}\n\n{summary_text}"
    return ModelRequest(parts=[UserPromptPart(content=content)])


# ── History replay ───────────────────────────────────────────────────

_COMPACTION_PREVIEW_CHARS = 200


def replay_history(
    emit: Callable[[Event], None],
    messages: list[ModelMessage],
) -> None:
    """Replay conversation history by emitting display events.

    Walks the message list and emits the same events the live path
    would produce — `InputEcho`, `MarkdownOutput`, `FlushPanel`,
    `ToolCallStarted`, `ToolCallFinished` — so the TUI renders
    history through a single rendering route.

    Uses exhaustive ``match`` with ``assert_never`` on both
    ``ModelRequestPart`` and ``ModelResponsePart`` unions so that
    mypy catches any unhandled part type.
    """
    # Pass 1: collect tool results by call ID.
    tool_results: dict[str, tuple[str, bool]] = {}
    for msg in messages:
        if not isinstance(msg, ModelRequest):
            continue
        for req_part in msg.parts:
            match req_part:
                case ToolReturnPart(tool_call_id=cid, content=content):
                    tool_results[cid] = (str(content), False)
                case RetryPromptPart(tool_call_id=cid, content=content):
                    tool_results[cid] = (str(content), True)
                case UserPromptPart() | SystemPromptPart():
                    pass
                case _:
                    assert_never(req_part)

    # Pass 2: walk messages and emit events.
    for msg in messages:
        if isinstance(msg, ModelRequest):
            _replay_request(emit, msg)
        elif isinstance(msg, ModelResponse):
            _replay_response(emit, msg, tool_results)


def _replay_request(
    emit: Callable[[Event], None],
    msg: ModelRequest,
) -> None:
    """Emit events for a single ``ModelRequest``."""
    for part in msg.parts:
        match part:
            case UserPromptPart(content=content):
                text = str(content)
                if is_compaction_summary(text):
                    preview = text[:_COMPACTION_PREVIEW_CHARS]
                    if len(text) > _COMPACTION_PREVIEW_CHARS:
                        preview += "…"
                    emit(Output(text=preview))
                    emit(FlushPanel(variant=PanelVariant.QUEUED))
                else:
                    emit(InputEcho(text=text))
            case SystemPromptPart() | ToolReturnPart() | RetryPromptPart():
                pass
            case _:
                assert_never(part)


def _replay_response(
    emit: Callable[[Event], None],
    msg: ModelResponse,
    tool_results: dict[str, tuple[str, bool]],
) -> None:
    """Emit events for a single ``ModelResponse``."""
    accumulated_text = ""
    for part in msg.parts:
        match part:
            case TextPart(content=content):
                accumulated_text += content
            case ToolCallPart(tool_name=name, args=args, tool_call_id=cid):
                if accumulated_text:
                    emit(MarkdownOutput(text=accumulated_text))
                    emit(FlushPanel(variant=PanelVariant.RESPONSE))
                    accumulated_text = ""
                emit(
                    ToolCallStarted(
                        tool_name=name,
                        args=format_tool_args(args),
                        tool_call_id=cid,
                    )
                )
                result_text, failed = tool_results.get(cid, ("", False))
                emit(
                    ToolCallFinished(
                        tool_name=name,
                        tool_call_id=cid,
                        result="" if failed else result_text,
                        error=result_text if failed else None,
                    )
                )
            case ThinkingPart() | BuiltinToolCallPart() | BuiltinToolReturnPart() | FilePart():
                pass
            case _:
                assert_never(part)

    if accumulated_text:
        emit(MarkdownOutput(text=accumulated_text))
        emit(FlushPanel(variant=PanelVariant.RESPONSE))
