name: CI

on:
  pull_request:
    branches:
      - "*"
  merge_group:

jobs:
  checks:
    if: >-
      !startsWith(github.head_ref, 'release-')
      && !startsWith(github.head_ref, 'pre-release-')
    uses: ./.github/workflows/checks.yaml
